image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2361.65135,    0.     ,  720.40631,
            0.     , 2357.69296,  536.09769,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.099697, 0.135729, -0.001890, 0.001278, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2340.61304,    0.     ,  720.77997,    0.     ,
            0.     , 2343.90918,  534.85141,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
